version: '3.8'

networks:
  # Red privada para la comunicación interna de la célula de perfiles
  profile-network:
    driver: bridge
  # Red compartida para conectarse a la célula de observabilidad
  observability-network:
    external: true

volumes:
  mongo-profile-data:
    driver: local

services:
  # --- Base de Datos dedicada para la Célula de Perfiles ---
  mongo_profile:
    image: mongo:latest
    container_name: mongo_profile
    restart: unless-stopped
    ports:
      - "27018:27017" # Puerto del host diferente para no chocar con la otra BD
    volumes:
      - mongo-profile-data:/data/db
    networks:
      - profile-network # La BD se mantiene aislada en su red privada

  # --- Microservicios de la Célula 2 (Conectados a ambas redes) ---

  profile-service:
    build:
      context: ./profile-service
    container_name: profile-service
    restart: unless-stopped
    networks:
      - profile-network
      - observability-network # <-- Conectado a la red compartida
    depends_on:
      - mongo_profile
    environment:
      - SERVER_PORT=8091
      - SPRING_DATA_MONGODB_URI=mongodb://mongo_profile:27017/profiles_db
    logging: 
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push" # <-- URL corregida

  # Aquí irían los otros servicios de la célula (file-service, dashboard-service)
  # file-service:
  #   ...
  # dashboard-service:
  #   ...

  profile-gateway:
    build:
      context: ./profile-gateway
    container_name: profile-gateway
    restart: unless-stopped
    ports:
      - "8090:8090" # Puerto de entrada para la Célula 2
    networks:
      - profile-network
      - observability-network # <-- Conectado a la red compartida
    depends_on:
      - profile-service
    environment:
      - SERVER_PORT=8090
    logging: 
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push" # <-- URL corregida