server:
  port: 8090

spring:
  application:
    name: cell-gateway
  cloud:
    discovery:
      client:
        simple:
          instances:
            profile-service:
              - uri: http://profile-service:8091
            file-service:
              - uri: http://file-service:8092
    gateway:
      routes:
        - id: profile-service
          uri: lb://profile-service
          predicates:
            - Path=/profile/api/v1/profiles/**
          filters:
            - StripPrefix=1
        - id: file-service
          uri: lb://file-service
          predicates:
            - Path=/profile/api/v1/files/**
          filters:
            - StripPrefix=1

management: # Configuracion del Actuator
  endpoints:
    web:
      exposure:
        include: prometheus, health, info, metrics, gateway, refresh