server:
  port: 8090

spring:
  application:
    name: cell-gateway
  cloud:
    gateway:
      routes:
        - id: profile-service
          uri: http://profile-service:8091
          predicates:
            - Path=/api/v1/profiles/**
        - id: file-service
          uri: http://file-service:8092
          predicates:
            - Path=/api/v1/files/**

management: # Configuracion del Actuator
  endpoints:
    web:
      exposure:
        include: prometheus, health, info, metrics, gateway, refresh